USE rolplay_edu;

DELETE FROM scenarios WHERE program_id IS NULL;

INSERT INTO scenarios (program_id, title, description, area, difficulty, steps_json, is_ai_generated, estimated_duration, active, created_at, updated_at)
VALUES
(NULL, 'Cambio de Requisitos', 'El cliente cambia prioridades a mitad del sprint.', 'tecnologia', 'intermedio',
 '[{"id":0,"text":"El cliente pide cambios urgentes que afectan el plan. Que haces primero?","options":[{"text":"A) Aceptar todo sin analizar","result":1,"feedback":"bad","scores":{"Comunicacion":-5,"Liderazgo":-5,"Trabajo en Equipo":-5,"Toma de Decisiones":-5}},{"text":"B) Analizar impacto y alinear con el equipo","result":1,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":8,"Trabajo en Equipo":6,"Toma de Decisiones":10}},{"text":"C) Ignorar el cambio","result":1,"feedback":"bad","scores":{"Comunicacion":-10,"Liderazgo":-6,"Trabajo en Equipo":-4,"Toma de Decisiones":-8}}]},{"id":1,"text":"El equipo esta confundido con la nueva prioridad.","options":[{"text":"A) Hacer una mini reunion y clarificar objetivos","result":2,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":10,"Trabajo en Equipo":8,"Toma de Decisiones":6}},{"text":"B) Dejar que cada quien interprete","result":2,"feedback":"neutral","scores":{"Comunicacion":0,"Liderazgo":0,"Trabajo en Equipo":-2,"Toma de Decisiones":-2}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"Una buena gestion del cambio combina analisis, comunicacion y acuerdos claros.","options":[]}]
 ', 0, 15, 1, NOW(), NOW()),

(NULL, 'Feedback Conflictivo', 'Debes dar retroalimentacion a un companero molesto.', 'comercio', 'basico',
 '[{"id":0,"text":"Un companero reacciona mal al feedback. Como inicias?","options":[{"text":"A) Le dices que se aguante","result":1,"feedback":"bad","scores":{"Comunicacion":-10,"Liderazgo":-4,"Trabajo en Equipo":-8,"Toma de Decisiones":-6}},{"text":"B) Preguntas como se siente y contextualizas","result":1,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":10,"Toma de Decisiones":6}}]},{"id":1,"text":"Necesitas ser claro sin herir.","options":[{"text":"A) Usar ejemplos concretos y proponer mejoras","result":2,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":8,"Trabajo en Equipo":6,"Toma de Decisiones":6}},{"text":"B) Hablar en generalidades","result":2,"feedback":"neutral","scores":{"Comunicacion":0,"Liderazgo":0,"Trabajo en Equipo":0,"Toma de Decisiones":0}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"El feedback efectivo es oportuno, especifico y empatico.","options":[]}]
 ', 0, 12, 1, NOW(), NOW()),

(NULL, 'Proveedor Inconfiable', 'Un proveedor incumple y pone en riesgo la entrega.', 'logistica', 'intermedio',
 '[{"id":0,"text":"El proveedor no responde. Que haces?","options":[{"text":"A) Esperar sin plan B","result":1,"feedback":"bad","scores":{"Comunicacion":-4,"Liderazgo":-6,"Trabajo en Equipo":-4,"Toma de Decisiones":-10}},{"text":"B) Escalar y activar alternativas","result":1,"feedback":"good","scores":{"Comunicacion":8,"Liderazgo":10,"Trabajo en Equipo":6,"Toma de Decisiones":10}}]},{"id":1,"text":"Debes informar a stakeholders.","options":[{"text":"A) Comunicar impacto y mitigacion","result":2,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":6,"Toma de Decisiones":8}},{"text":"B) Ocultar el problema","result":2,"feedback":"bad","scores":{"Comunicacion":-10,"Liderazgo":-6,"Trabajo en Equipo":-6,"Toma de Decisiones":-8}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"La gestion de riesgos exige transparencia y decisiones oportunas.","options":[]}]
 ', 0, 18, 1, NOW(), NOW()),

(NULL, 'Error en Produccion', 'Se detecta un fallo critico en un sistema en uso.', 'tecnologia', 'avanzado',
 '[{"id":0,"text":"Hay un error critico. Tu primer paso?","options":[{"text":"A) Buscar culpables","result":1,"feedback":"bad","scores":{"Comunicacion":-8,"Liderazgo":-8,"Trabajo en Equipo":-10,"Toma de Decisiones":-4}},{"text":"B) Contener el impacto y abrir incidente","result":1,"feedback":"good","scores":{"Comunicacion":8,"Liderazgo":10,"Trabajo en Equipo":10,"Toma de Decisiones":10}}]},{"id":1,"text":"El equipo necesita direccion.","options":[{"text":"A) Asignar roles y tiempos claros","result":2,"feedback":"good","scores":{"Comunicacion":8,"Liderazgo":10,"Trabajo en Equipo":8,"Toma de Decisiones":8}},{"text":"B) Dejar que todo fluya","result":2,"feedback":"neutral","scores":{"Comunicacion":0,"Liderazgo":-2,"Trabajo en Equipo":-2,"Toma de Decisiones":-4}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"En crisis: primero contener, luego comunicar, despues aprender.","options":[]}]
 ', 0, 20, 1, NOW(), NOW()),

(NULL, 'Idea Rechazada', 'Tu propuesta fue rechazada en una reunion.', 'comercio', 'basico',
 '[{"id":0,"text":"Rechazan tu idea. Como respondes?","options":[{"text":"A) Te ofendes y te cierras","result":1,"feedback":"bad","scores":{"Comunicacion":-8,"Liderazgo":-4,"Trabajo en Equipo":-8,"Toma de Decisiones":-4}},{"text":"B) Pides criterios y aprendes","result":1,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":6,"Toma de Decisiones":8}}]},{"id":1,"text":"Quieres mejorarla.","options":[{"text":"A) Iterar con feedback y datos","result":2,"feedback":"good","scores":{"Comunicacion":8,"Liderazgo":6,"Trabajo en Equipo":8,"Toma de Decisiones":8}},{"text":"B) Guardarla sin accion","result":2,"feedback":"neutral","scores":{"Comunicacion":0,"Liderazgo":0,"Trabajo en Equipo":0,"Toma de Decisiones":-2}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"La resiliencia convierte el rechazo en aprendizaje accionable.","options":[]}]
 ', 0, 10, 1, NOW(), NOW()),

(NULL, 'Companero con Dificultades', 'Un companero esta bajando su rendimiento.', 'servicio', 'intermedio',
 '[{"id":0,"text":"Notas que alguien no esta bien. Que haces?","options":[{"text":"A) Ignorar para no meterte","result":1,"feedback":"bad","scores":{"Comunicacion":-6,"Liderazgo":-4,"Trabajo en Equipo":-10,"Toma de Decisiones":-4}},{"text":"B) Conversar en privado con respeto","result":1,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":10,"Toma de Decisiones":6}}]},{"id":1,"text":"Hay barreras personales y de trabajo.","options":[{"text":"A) Ofrecer apoyo y ajustar expectativas","result":2,"feedback":"good","scores":{"Comunicacion":8,"Liderazgo":8,"Trabajo en Equipo":10,"Toma de Decisiones":6}},{"text":"B) Reportar sin hablar antes","result":2,"feedback":"neutral","scores":{"Comunicacion":-2,"Liderazgo":2,"Trabajo en Equipo":-4,"Toma de Decisiones":0}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"El apoyo oportuno fortalece la cohesion del equipo.","options":[]}]
 ', 0, 16, 1, NOW(), NOW()),

(NULL, 'Prioridades del Proyecto', 'Exceso de tareas y todas parecen urgentes.', 'tecnologia', 'intermedio',
 '[{"id":0,"text":"Todo parece urgente. Como priorizas?","options":[{"text":"A) Hacer lo primero que llegue","result":1,"feedback":"bad","scores":{"Comunicacion":-2,"Liderazgo":-6,"Trabajo en Equipo":-2,"Toma de Decisiones":-10}},{"text":"B) Usar criterios claros de impacto y esfuerzo","result":1,"feedback":"good","scores":{"Comunicacion":6,"Liderazgo":10,"Trabajo en Equipo":6,"Toma de Decisiones":10}}]},{"id":1,"text":"Necesitas alinear al equipo.","options":[{"text":"A) Explicar prioridades y por que","result":2,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":8,"Trabajo en Equipo":8,"Toma de Decisiones":8}},{"text":"B) Imponer sin contexto","result":2,"feedback":"neutral","scores":{"Comunicacion":-4,"Liderazgo":4,"Trabajo en Equipo":-4,"Toma de Decisiones":0}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"Priorizar bien es decidir con criterios y comunicar el por que.","options":[]}]
 ', 0, 14, 1, NOW(), NOW()),

(NULL, 'Presentacion Inesperada', 'Debes presentar avances sin preparacion previa.', 'comunicacion', 'basico',
 '[{"id":0,"text":"Te piden presentar ya. Tu enfoque inicial?","options":[{"text":"A) Improvisar sin estructura","result":1,"feedback":"neutral","scores":{"Comunicacion":0,"Liderazgo":0,"Trabajo en Equipo":0,"Toma de Decisiones":0}},{"text":"B) Organizar 3 ideas clave y objetivo","result":1,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":4,"Toma de Decisiones":8}}]},{"id":1,"text":"Durante preguntas, hay tension.","options":[{"text":"A) Escuchar, confirmar y responder breve","result":2,"feedback":"good","scores":{"Comunicacion":10,"Liderazgo":6,"Trabajo en Equipo":6,"Toma de Decisiones":6}},{"text":"B) Defenderte atacando","result":2,"feedback":"bad","scores":{"Comunicacion":-10,"Liderazgo":-4,"Trabajo en Equipo":-6,"Toma de Decisiones":-4}}]},{"id":2,"text":"Cierre del caso.","feedbackText":"Una estructura simple y la escucha activa salvan presentaciones inesperadas.","options":[]}]
 ', 0, 12, 1, NOW(), NOW());